[package]
name = "wasm-only-draws"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = {version = "1.21.0", features = ["derive"] }
pollster = "0.4.0"
rand = "0.8.5"
wgpu = "23.0.1"
winit = "0.30.7"
